FROM ghcr.io/%%GITHUB_OWNER%%/retro-toolchain/base

RUN apt update && apt install -y \
    git \
    file \
    wget \
    cpio \
    python \
    unzip \
    rsync \
    mercurial \
    u-boot-tools \
    vorbis-tools \
    && rm -rf /var/lib/apt/lists/*

