FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=Etc/UTC

RUN apt-get update && apt-get install -y \
    file \
    build-essential \
    gcc-multilib \
    g++-multilib \
    bc \
    libncurses5-dev \
    libncursesw5-dev \
    libssl-dev \
    git \
    cmake \
    && rm -rf /var/lib/apt/lists/*
