FROM ghcr.io/%%GITHUB_OWNER%%/retro-toolchain/base

RUN apt update && apt install -y \
    file \
    wget \
    cpio \
    python3 \
    zip \
    unzip \
    rar \
    unrar \
    p7zip-full \
    rsync \
    mercurial \
    u-boot-tools \
    vorbis-tools \
    && rm -rf /var/lib/apt/lists/*

