FROM ghcr.io/%%GITHUB_OWNER%%/retro-toolchain/base

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    expect \
    file \
    wget \
    cpio \
    python3 \
    unzip \
    rsync \
    mercurial \
    u-boot-tools \
    && rm -rf /var/lib/apt/lists/*

